export const robots = [
    {
        id: "5ef5da65a7929e7a3e361daa",
        name: "Jewell Calhoun",
        username: "Pena Reese",
        email: "penareese@permadyne.com",
    },
    {
        id: "5ef5da657ca4ac3ee2c1566f",
        name: "Nora Short",
        username: "Cherry Macias",
        email: "cherrymacias@permadyne.com",
    },
    {
        id: "5ef5da650bf121f2fc689816",
        name: "Rowena Alvarez",
        username: "Mccarty Woodard",
        email: "mccartywoodard@permadyne.com",
    },
    {
        id: "5ef5da659076d06d5e3e5f8f",
        name: "Lauri Roth",
        username: "Burris Monroe",
        email: "burrismonroe@permadyne.com",
    },
    {
        id: "5ef5da65aaa00aad661da844",
        name: "Cooley Lowery",
        username: "Jackie Sweet",
        email: "jackiesweet@permadyne.com",
    },
    {
        id: "5ef5da65c60699be8c81431c",
        name: "Solomon Mcdaniel",
        username: "Selena Huffman",
        email: "selenahuffman@permadyne.com",
    },
    {
        id: "5ef5da655e4208cc1c69484a",
        name: "Kathrine Gillespie",
        username: "Nixon Olsen",
        email: "nixonolsen@permadyne.com",
    },
    {
        id: "5ef5da65db92c2f10044eb5f",
        name: "Harvey Eaton",
        username: "Lara Mcgowan",
        email: "laramcgowan@permadyne.com",
    },
    {
        id: "5ef5da652c8016be1cd424eb",
        name: "Dolly Salazar",
        username: "Holloway Mclaughlin",
        email: "hollowaymclaughlin@permadyne.com",
    },
    {
        id: "5ef5da65b762d818da339230",
        name: "Cora Sellers",
        username: "Winters Mcleod",
        email: "wintersmcleod@permadyne.com",
    },
    {
        id: "5ef5da65583e5f94a20ef94c",
        name: "Lowery Cantu",
        username: "Savannah Cooper",
        email: "savannahcooper@permadyne.com",
    },
    {
        id: "5ef5da65550a5ec3fdef3d74",
        name: "Castillo Phillips",
        username: "Vera Sullivan",
        email: "verasullivan@permadyne.com",
    },
    {
        id: "5ef5da6591d09da47acc610a",
        name: "Craft Pearson",
        username: "Kara Downs",
        email: "karadowns@permadyne.com",
    },
    {
        id: "5ef5da65988e946e6f3d5e66",
        name: "Miller Contreras",
        username: "Cole Barker",
        email: "colebarker@permadyne.com",
    },
    {
        id: "5ef5da65d71143dc5cc77559",
        name: "Rojas Odom",
        username: "Emerson Gardner",
        email: "emersongardner@permadyne.com",
    },
    {
        id: "5ef5da657af83a0331568415",
        name: "Maryellen Tanner",
        username: "Jacobs Ramirez",
        email: "jacobsramirez@permadyne.com",
    },
    {
        id: "5ef5da657bde9613d510bb79",
        name: "Mcbride Wheeler",
        username: "Jimenez Herman",
        email: "jimenezherman@permadyne.com",
    },
    {
        id: "5ef5da659fed0ff38eb0f633",
        name: "Pansy Hunter",
        username: "Burch Hess",
        email: "burchhess@permadyne.com",
    },
    {
        id: "5ef5da65a3265c39ad4b135f",
        name: "Maureen May",
        username: "Corrine Talley",
        email: "corrinetalley@permadyne.com",
    },
];
